name: Push Beta Release

on:
  push:
    tags:
      - 'v*-beta'

permissions:
  contents: write

env:
  ORIGIN: origin
  MAKE_APP_CONF: .github/scripts/make-app-conf.py
  APP_CONF: conf.json
  CHANGE_LOG: CHANGELOG.md

jobs:
  boot:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-vars.outputs.version }}

    steps:
      - name: Extract variables
        id: extract-vars
        run: |
          VERSION=$(echo ${{ github.ref }} | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo -e "v $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  fork-main:
    needs: boot
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for merging
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout beta branch
        run: git checkout beta

      - name: Merge main into beta
        run: |
          git merge -s ours ${{ env.ORIGIN }}/main --no-commit --no-ff || echo "CONFLICT"
          git checkout ${{ env.ORIGIN }}/main -- .

      - name: Add version info
        run: |
          VERSION=${{ needs.boot.outputs.version }}
          echo -e "v $VERSION"
          echo -e "<<<<\e[32m"
          cat ${{ env.APP_CONF }}
          echo -e ""
          echo -e "\e[0m----\e[36m"
          cat ${{ env.APP_CONF }} | python ${{ env.MAKE_APP_CONF }} $VERSION > ${{ env.APP_CONF }}.new
          mv ${{ env.APP_CONF }}.new ${{ env.APP_CONF }}
          cat ${{ env.APP_CONF }}
          echo -e ""
          echo -e "\e[0m>>>>"
          git add ${{ env.APP_CONF }}

      - name: Add change log
        run: |
          VERSION=${{ needs.boot.outputs.version }}
          PREV_REV=$(git rev-parse HEAD)
          echo -e "prev_rev $PREV_REV"
          echo -e "# $VERSION CHANGELOG" > ${{ env.CHANGE_LOG }}
          echo -e "" >> ${{ env.CHANGE_LOG }}
          git log $PREV_REV..${{ env.ORIGIN }}/HEAD --pretty="format:- %s - by *%ae* at %aD" >> ${{ env.CHANGE_LOG }}
          echo -e "----"
          cat ${{ env.CHANGE_LOG }}
          echo -e "----"
          git add ${{ env.CHANGE_LOG }}

      - name: Commit changes
        run: |
          VERSION=${{ needs.boot.outputs.version }}
          git commit -m "$VERSION"

      - name: Push changes
        run: git push ${{ env.ORIGIN }} beta
  
  send-news:
    runs-on: ubuntu-latest
    needs: 
      - boot
      - fork-main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout beta branch
        run: git checkout beta
      
      - name: Mail change log
        run: |
          VERSION=${{ needs.boot.outputs.version }}
          echo -e "Title: Beta $VERSION was just released"
          echo -e "To: abc@mail.net, def@mail.net"
          echo -e "Body:"
          cat ${{ env.CHANGE_LOG }}
          echo -e "."

  build-app:
    runs-on: ubuntu-latest
    needs: fork-main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout beta branch
        run: git checkout beta
      
      - name: Prebuild
        run: |
          echo -e "Prebuilding..."
          sleep 10
      
      - name: Build for X
        run: |
          echo -e "Handing off the build..."
          cat res/files.yaml
          sleep 5
      
      - name: Build for Y
        run: |
          echo -e "Handing off the build..."
          cat res/files.yaml
          sleep 5